### ISSUE TITLE
ES 6.2.2 error installing plugin

### ISSUE THREAD

**Issue by calston** [ForgeRock/es-change-feed-plugin#12]
```
-> Downloading https://github.com/ForgeRock/es-change-feed-plugin/releases/download/v6.2.2/es-changes-feed-plugin.zip
Retrieving zip from https://github.com/ForgeRock/es-change-feed-plugin/releases/download/v6.2.2/es-changes-feed-plugin.zip
[=================================================] 100%?? 
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:297)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

```

**Comment by jurgc11** [comment]
I haven't had time to test with 6.x yet. It may be as simple as removing that property from here and rebuilding https://github.com/ForgeRock/es-change-feed-plugin/blob/master/src/main/resources/plugin-descriptor.properties

**Comment by calston** [comment]
Yes it's truly wonderful that this plugin API changes every version, and minor version, and with the phase of the moon. :/

**Comment by dhruvdcoder** [comment]
Removing the 'jvm=true' worked for me for ES 6.2.4.
Ref: [https://www.elastic.co/guide/en/elasticsearch/plugins/6.2/plugin-authors.html#_plugin_descriptor_file](https://www.elastic.co/guide/en/elasticsearch/plugins/6.2/plugin-authors.html#_plugin_descriptor_file)
